### ISSUE TITLE
[ADD DOCKER] Add docker image.

### ISSUE THREAD

**Issue by mariushosting** [markrai/fontcompare#6]
Add Docker image for this good app!

**Comment by Itz-Agasta** [comment]
> > Hi @markrai, I have created the [docker image](https://github.com/markrai/fontcompare/pull/7) as @mariushosting asked. Can you please review it? and let me know if you want me to update the `Readme.md`
> 
> fontcompare-web, repository does not exist

Sorry didn't get it .. can you please elaborate?

**Comment by mariushosting** [comment]
> > > Hi @markrai, I have created the [docker image](https://github.com/markrai/fontcompare/pull/7) as @mariushosting asked. Can you please review it? and let me know if you want me to update the `Readme.md`
> > 
> > 
> > fontcompare-web, repository does not exist
> 
> Sorry didn't get it .. can you please elaborate?

The image is not available and can't be downloaded did you put it online? Just asking.

**Comment by Itz-Agasta** [comment]
> > > > Hi @markrai, I have created the [docker image](https://github.com/markrai/fontcompare/pull/7) as @mariushosting asked. Can you please review it? and let me know if you want me to update the `Readme.md`
> > > 
> > > 
> > > fontcompare-web, repository does not exist
> > 
> > 
> > Sorry didn't get it .. can you please elaborate?
> 
> The image is not available and can't be downloaded did you put it online? Just asking.

Actually I have created the PR on this repo. And it's not merge yet ... If you want to use it you can fork this repo form my profile... Or if you want I can upload the image on dockerhub ... I guess 2 nd way will be great.

**Comment by mariushosting** [comment]
> > > > > Hi @markrai, I have created the [docker image](https://github.com/markrai/fontcompare/pull/7) as @mariushosting asked. Can you please review it? and let me know if you want me to update the `Readme.md`
> > > > 
> > > > 
> > > > fontcompare-web, repository does not exist
> > > 
> > > 
> > > Sorry didn't get it .. can you please elaborate?
> > 
> > 
> > The image is not available and can't be downloaded did you put it online? Just asking.
> 
> Actually I have created the PR on this repo. And it's not merge yet ... If you want to use it you can fork this repo form my profile... Or if you want I can upload the image on dockerhub ... I guess 2 nd way will be great.

Thank you for Clarifying!!

**Comment by Itz-Agasta** [comment]
> > > > > > Hi @markrai, I have created the [docker image](https://github.com/markrai/fontcompare/pull/7) as @mariushosting asked. Can you please review it? and let me know if you want me to update the `Readme.md`
> > > > > 
> > > > > 
> > > > > fontcompare-web, repository does not exist
> > > > 
> > > > 
> > > > Sorry didn't get it .. can you please elaborate?
> > > 
> > > 
> > > The image is not available and can't be downloaded did you put it online? Just asking.
> > 
> > 
> > Actually I have created the PR on this repo. And it's not merge yet ... If you want to use it you can fork this repo form my profile... Or if you want I can upload the image on dockerhub ... I guess 2 nd way will be great.
> 
> Thank you for Clarifying!!

Okay, so do you want me to upload the Docker image into the Docker Hub, or will you check it out from my repo, https://github.com/Itz-Agasta/fontcompare?

**Comment by mariushosting** [comment]
> > > > > > > Hi @markrai, I have created the [docker image](https://github.com/markrai/fontcompare/pull/7) as @mariushosting asked. Can you please review it? and let me know if you want me to update the `Readme.md`
> > > > > > 
> > > > > > 
> > > > > > fontcompare-web, repository does not exist
> > > > > 
> > > > > 
> > > > > Sorry didn't get it .. can you please elaborate?
> > > > 
> > > > 
> > > > The image is not available and can't be downloaded did you put it online? Just asking.
> > > 
> > > 
> > > Actually I have created the PR on this repo. And it's not merge yet ... If you want to use it you can fork this repo form my profile... Or if you want I can upload the image on dockerhub ... I guess 2 nd way will be great.
> > 
> > 
> > Thank you for Clarifying!!
> 
> Okay, so do you want me to upload the Docker image into the Docker Hub, or will you check it out from my repo, https://github.com/Itz-Agasta/fontcompare?

Better to upload on the Docker Hub

**Comment by mariushosting** [comment]
> > > > > > > > > Hi @markrai, I have created the [docker image](https://github.com/markrai/fontcompare/pull/7) as @mariushosting asked. Can you please review it? and let me know if you want me to update the `Readme.md`
> > > > > > > > 
> > > > > > > > 
> > > > > > > > fontcompare-web, repository does not exist
> > > > > > > 
> > > > > > > 
> > > > > > > Sorry didn't get it .. can you please elaborate?
> > > > > > 
> > > > > > 
> > > > > > The image is not available and can't be downloaded did you put it online? Just asking.
> > > > > 
> > > > > 
> > > > > Actually I have created the PR on this repo. And it's not merge yet ... If you want to use it you can fork this repo form my profile... Or if you want I can upload the image on dockerhub ... I guess 2 nd way will be great.
> > > > 
> > > > 
> > > > Thank you for Clarifying!!
> > > 
> > > 
> > > Okay, so do you want me to upload the Docker image into the Docker Hub, or will you check it out from my repo, https://github.com/Itz-Agasta/fontcompare?
> > 
> > 
> > Better to upload on the Docker Hub
> 
> Its done. here you go https://hub.docker.com/r/agasta/fontcompare .. or you can just run this cmd in your terminal
> 
> ```shell
> docker pull agasta/fontcompare 
> ```

Works like a charm! Thank you!

**Comment by markrai** [comment]
@mariushosting 
Thank you, sir! And a double-thank you for being a guiding light all these years on Synology!

@Itz-Agasta - It's been merged :)
